### ISSUE TITLE
Rename Spacemesh App

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/testnet-guide#14]
The name is too generic, hard to Google, etc. I propose the name "Glass" (from "Through the Looking Glass"). It's transparent, and clear, and approachable, and it's the portal through which you access the Spacemesh ecosystem. Ethereum's first UI was called Myst; "Glass" is more transparent ;) There's also a pun on "Windows" in there somewhere ;)

Source: https://docs.google.com/document/d/1rL3susWJajibpVKiefKNiStfdyQSQu5klhicbFsk8Nc/edit?disco=AAAADg4UsVI

**Comment by avive** [comment]
A bit too late for this for 0.1 in the cycle - consider for 0.2 for sure.

**Comment by avive** [comment]
We should move this to product repo.

**Comment by avive** [comment]
The problem with glass is that it is the opposite of the app visual design concept which is retro and opaque. I suggest we'll move this discussion to a Smip from this repo.

**Comment by lrettig** [comment]
Some other proposed names, all mirror-related: Speculum (the "sp"
alliteration is nice), Amalgam, Sublime/Sublimate, Parabola

>

**Comment by avive** [comment]
Moving the issue to smapp.
